gha: build: install dotenv 2.8.1 for fpm
```
Step 22/23 : RUN gem install fpm
 ---> Running in 9f43093191b9
ERROR:  Error installing fpm:
	The last version of dotenv (>= 0) to support your Ruby & RubyGems was 2.8.1. Try installing it with `gem install dotenv -v 2.8.1` and then running the current command again
	dotenv requires Ruby version >= 3.0. The current ruby version is 2.6.9.207.
```